# Data checks and debugging

In [15]:
from IPython.display import display
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [20]:
pd.set_option('max_columns', None)

cleaned_data_filepath = '../data/sample-preprocessed.csv'
df = pd.read_csv(cleaned_data_filepath, dtype='str')
print(df.shape)
df

(17, 49)

,Duration (in seconds),Finished,RecordedDate,ResponseId,intro-1,intro-2,download,download-fail-expl,download-fail-screen_Id,download-fail-screen_Name,download-fail-screen_Size,download-fail-screen_Type,q-demos-age,Q-demos-hispanic,Q-demos-race,Q-demos-education,Q-demos-income,Q-demos-gender,Q-sexual-orientation,Q-demos-state,Q-amazon-use-howmany,Q-amazon-use-hh-size,Q-amazon-use-how-oft,Q-substance-use_1,Q-substance-use_2,Q-substance-use_3,Q-personal_1,Q-personal_2,Q-life-changes,Q-control,Q-altruism,Q-bonus-05,Q-bonus-20,Q-bonus-50,Q-data-value-05,Q-data-value-20,Q-data-value-50,Q-data-value-100,Q-data-value-any,Q-data-value-any_1_TEXT,Q-sell-YOUR-data,Q-sell-consumer-data,Q-small-biz-use,Q-census-use,Q-research-society,Q-attn-check,showdata,incentive,RandomID
0,45,1,2022-09-13 08:39:39,R_2ykJU7y9XoyCZTk,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,altruism,NaN
1,288,1,2022-09-13 08:44:33,R_BV7CBQjtGOjHZF7,4,1,2,test problem flow by alex,F_YVTItdPN6hSEAkp,Screen Shot 2022-09-12 at 4.56.40 PM.png,53964,image/png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,true,altruism,NaN
2,239,1,2022-09-13 08:48:35,R_w4seX0QuU1Lz477,4,1,1,NaN,NaN,NaN,NaN,NaN,2,2,"1,6",4,2,2,2,22,1,1,1,2,2,2,2,2,3,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,4,13,3,3,"1,2,3",false,bonus-20,199989274
3,335,1,2022-09-13 11:11:52,R_2rBGztPmiRoLHWj,4,1,1,NaN,NaN,NaN,NaN,NaN,2,2,1,4,2,1,1,22,2,2,2,2,2,1,2,2,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,1,1,1,"1,2,3",false,bonus-05,689693001
4,1321,1,2022-09-13 12:49:38,R_1OkQY5Lrzb43QtM,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,control,NaN
5,5,1,2022-09-20 10:17:28,R_yNDhvjRSzYmGhRn,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,true,bonus-50,924917061
6,284,1,2022-09-20 10:22:24,R_UMxN4WvUfxyPh0l,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,true,bonus-20,584870166
7,4,1,2022-09-20 10:22:38,R_ykzEFr5Ol0wR9UR,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,altruism,677091350
8,10,1,2022-09-20 10:22:55,R_D79R4nSXTyQ8AwN,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,bonus-05,428372309
9,144,1,2022-09-20 10:25:23,R_1lrD8rMITN9ynoB,4,1,1,NaN,NaN,NaN,NaN,NaN,2,1,4,5,4,4,1,22,1,1,1,2,2,2,3,2,4,0,NaN,NaN,NaN,NaN,0,1,NaN,NaN,NaN,NaN,3,2,13,3,3,"1,2,3",true,control,324010531
10,410,1,2022-09-20 10:34:45,R_3NTZn3wLkqaN0cV,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,true,altruism,772445437
11,3,1,2022-09-20 10:34:51,R_6EShSpSQnZhYrrX,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,true,bonus-50,957466248
12,4,1,2022-09-20 10:37:51,R_vICdKBAGcHc04xj,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,bonus-05,645843676
13,4,1,2022-09-20 10:38:13,R_1hKky5J1PfnKbVE,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,control,415290043
14,10,1,2022-09-20 10:40:01,R_8BRoAZtMAvnYna9,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,true,control,978143164
15,59,1,2022-09-20 10:41:04,R_2bOclY6yJ6uno5H,4,1,2,test if randomID will be shown,F_2YXoy4cy2dLgd4T,Screen Shot 2022-09-14 at 2.17.45 PM.png,3981,image/png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,bonus-20,504695955
16,147,1,2022-09-20 10:43:41,R_3rGrAC7buWarniN,4,1,1,NaN,NaN,NaN,NaN,NaN,5,1,"1,6",3,7,3,3,1,2,4,1,1,1,1,1,1,2,NaN,0,NaN,NaN,NaN,0,0,0,0,1,20,2,4,1,3,1,3,false,altruism,629716286

All data should have a random ID

In [18]:
df[['RandomID', 'download', 'RecordedDate']]

     RandomID download         RecordedDate
0         NaN      NaN  2022-09-13 08:39:39
1         NaN        2  2022-09-13 08:44:33
2   199989274        1  2022-09-13 08:48:35
3   689693001        1  2022-09-13 11:11:52
4         NaN      NaN  2022-09-13 12:49:38
5   924917061      NaN  2022-09-20 10:17:28
6   584870166      NaN  2022-09-20 10:22:24
7   677091350      NaN  2022-09-20 10:22:38
8   428372309      NaN  2022-09-20 10:22:55
9   324010531        1  2022-09-20 10:25:23
10  772445437      NaN  2022-09-20 10:34:45
11  957466248      NaN  2022-09-20 10:34:51
12  645843676      NaN  2022-09-20 10:37:51
13  415290043      NaN  2022-09-20 10:38:13
14  978143164      NaN  2022-09-20 10:40:01
15  504695955        2  2022-09-20 10:41:04
16  629716286        1  2022-09-20 10:43:41